title: Jiao Meng
logo: "/images/website logo.png?raw=true"
description: >
   I am a passionate and data-driven analytics professional with a strong background in BI analytics, data visualization, and data modeling. 
   I am dedicated to leveraging data for strategic decision-making. 
   I can combine technical skills with a deep understanding of data to drive meaningful insights.
   <br><br>
   <a href="https://www.linkedin.com/in/jiao-meng/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-G0SDTGEHWR
